-- =============================================================================
-- Migration 008: Orders, Order Items, Status History, Payments
-- =============================================================================
-- Depends on: 001, 002, 003, 004, 006, 007
-- Creates: orders, order_items, order_status_history, payments
-- Also: resolves deferred FKs for inventory_transactions and coupon_usage
--
-- ADDRESS SNAPSHOT DECISION:
--   Chosen: Inline columns on orders (prefixed snapshot_).
--   Rationale:
--     - A separate order_address_snapshots table would be a strict 1:1 with
--       orders, adding a JOIN for every order query with no normalisation gain
--       (the data is never shared across orders).
--     - Inline columns keep a complete order record in one row, which is
--       simpler, faster to query, and easier to audit.
--     - The snapshot prefix clearly communicates that these fields are
--       immutable point-in-time copies.
--   This decision is documented in docs/DATABASE_ARCHITECTURE.md.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- TABLE: orders
-- Central order record. Created atomically by the Place Order Edge Function.
--
-- All monetary values in INTEGER PAISE. Cannot be negative.
--
-- order_number: human-readable unique identifier (e.g. ORX-20240101-0001).
--   Generated by the Edge Function. Must be unique. Stored as TEXT to support
--   any format without schema changes.
--
-- user_id ON DELETE RESTRICT: prevents auth user deletion while orders exist.
--   Account deletion flow must check for active orders first (documented in
--   FEATURE_BEHAVIOUR.md). After all orders reach a terminal state, the Edge
--   Function soft-deletes the profile and deletes the auth user.
--
-- address_id: nullable FK to user_addresses. If the user later deletes their
--   address, this FK becomes a dangling reference (the address row is deleted
--   but the order remains valid via its address snapshot columns).
--   ON DELETE SET NULL: avoids a FK violation when address is deleted.
--   Historical delivery information is always readable from snapshot columns.
--
-- coupon_id: nullable FK to coupons. ON DELETE SET NULL: coupon can be
--   deactivated/deleted without affecting existing orders.
--
-- Idempotency key: (user_id, idempotency_key) UNIQUE prevents duplicate
--   orders from the same Place Order request (see PRD Section 9.3).
--   The key is a UUID generated by the mobile client per checkout session.
--
-- snapshot_ columns: immutable point-in-time copy of the delivery address
--   at the time of order creation. Never updated after INSERT.
--
-- Total consistency:
--   subtotal_paise - coupon_discount_paise + delivery_charge_paise = total_paise
--   This is enforced by the Edge Function, not a DB CHECK (because rounding
--   may cause minor discrepancies). The Edge Function is the authoritative
--   calculator.
-- ---------------------------------------------------------------------------
CREATE TABLE orders (
    id                          UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number                TEXT            NOT NULL UNIQUE,
    user_id                     UUID            NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,

    -- FK to the user_addresses row selected at checkout (nullable; historical reference only)
    address_id                  UUID            REFERENCES user_addresses(id) ON DELETE SET NULL,

    coupon_id                   UUID            REFERENCES coupons(id) ON DELETE SET NULL,
    status                      order_status    NOT NULL DEFAULT 'pending',
    payment_method              payment_method  NOT NULL DEFAULT 'cash_on_delivery',
    payment_status              payment_status  NOT NULL DEFAULT 'pending',

    -- Financial summary (all integer paise, non-negative)
    subtotal_paise              INTEGER         NOT NULL,
    product_discount_paise      INTEGER         NOT NULL DEFAULT 0,    -- MRP - selling_price across items
    coupon_discount_paise       INTEGER         NOT NULL DEFAULT 0,
    delivery_charge_paise       INTEGER         NOT NULL DEFAULT 0,
    total_paise                 INTEGER         NOT NULL,

    -- Optional customer note (free text, no PII concerns)
    customer_note               TEXT,

    -- Idempotency key from mobile client (UUID per checkout session)
    idempotency_key             TEXT            NOT NULL,

    -- Immutable address snapshot (copied from user_addresses at order creation)
    snapshot_full_name          TEXT            NOT NULL,
    snapshot_phone              TEXT            NOT NULL,
    snapshot_address_line_1     TEXT            NOT NULL,
    snapshot_address_line_2     TEXT,
    snapshot_landmark           TEXT,
    snapshot_city               TEXT            NOT NULL,
    snapshot_state              TEXT            NOT NULL,
    snapshot_postal_code        TEXT            NOT NULL,
    snapshot_country_code       TEXT            NOT NULL DEFAULT 'IN',
    snapshot_address_type       address_type    NOT NULL DEFAULT 'home',

    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    cancelled_at                TIMESTAMPTZ,
    delivered_at                TIMESTAMPTZ,

    -- Money constraints
    CONSTRAINT chk_orders_subtotal             CHECK (subtotal_paise >= 0),
    CONSTRAINT chk_orders_product_discount     CHECK (product_discount_paise >= 0),
    CONSTRAINT chk_orders_coupon_discount      CHECK (coupon_discount_paise >= 0),
    CONSTRAINT chk_orders_delivery_charge      CHECK (delivery_charge_paise >= 0),
    CONSTRAINT chk_orders_total                CHECK (total_paise >= 0),

    -- Idempotency: same user cannot have two orders with the same key
    CONSTRAINT uq_orders_idempotency           UNIQUE (user_id, idempotency_key),

    -- Terminal state consistency
    CONSTRAINT chk_orders_cancelled_at
        CHECK (cancelled_at IS NULL OR status = 'cancelled'),
    CONSTRAINT chk_orders_delivered_at
        CHECK (delivered_at IS NULL OR status = 'delivered')
);

COMMENT ON TABLE orders IS
    'Order record created atomically by the Place Order Edge Function. '
    'All monetary values in integer paise. Address snapshot columns are '
    'immutable copies taken at order creation time — never updated.';

COMMENT ON COLUMN orders.idempotency_key IS
    'UUID generated by the mobile client per checkout session. '
    'UNIQUE (user_id, idempotency_key) prevents duplicate order creation.';

COMMENT ON COLUMN orders.address_id IS
    'Nullable FK to user_addresses. Historical reference only. '
    'ON DELETE SET NULL: address deletion does not break existing orders. '
    'All delivery information is duplicated in snapshot_ columns.';

COMMENT ON COLUMN orders.snapshot_full_name IS
    'Immutable copy of the delivery address at order creation. '
    'Never modified after INSERT. Read independently of user_addresses.';

-- ---------------------------------------------------------------------------
-- TABLE: order_items
-- Immutable snapshot of each product purchased.
--
-- product_id: nullable FK. ON DELETE SET NULL allows a product to be
--   hard-deleted in a rare emergency without breaking order history.
--   In normal operation, products are archived (archived_at IS NOT NULL)
--   and never hard-deleted, so this FK remains populated.
--   The snapshot columns ensure order history never depends on the current
--   state of the products table.
--
-- Snapshot columns: populated at order creation from current product data.
--   These values are NEVER updated. Any product change after order creation
--   does not affect order_items.
--
-- line_subtotal_paise = selling_price_paise_snapshot * quantity
-- line_discount_paise = (mrp_paise_snapshot - selling_price_paise_snapshot) * quantity
-- line_total_paise    = line_subtotal_paise (no item-level coupons in v1)
-- ---------------------------------------------------------------------------
CREATE TABLE order_items (
    id                              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id                        UUID        NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
    product_id                      UUID        REFERENCES products(id) ON DELETE SET NULL,

    -- Immutable product snapshot
    product_name_snapshot           TEXT        NOT NULL,
    sku_snapshot                    TEXT        NOT NULL,
    image_url_snapshot              TEXT,
    pack_size_snapshot              TEXT,
    mrp_paise_snapshot              INTEGER     NOT NULL,
    selling_price_paise_snapshot    INTEGER     NOT NULL,

    quantity                        INTEGER     NOT NULL,
    line_subtotal_paise             INTEGER     NOT NULL,   -- selling_price * quantity
    line_discount_paise             INTEGER     NOT NULL DEFAULT 0,
    line_total_paise                INTEGER     NOT NULL,

    created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Quantity and money constraints
    CONSTRAINT chk_order_items_quantity                 CHECK (quantity > 0),
    CONSTRAINT chk_order_items_mrp_positive             CHECK (mrp_paise_snapshot > 0),
    CONSTRAINT chk_order_items_selling_price_positive   CHECK (selling_price_paise_snapshot > 0),
    CONSTRAINT chk_order_items_selling_lte_mrp          CHECK (selling_price_paise_snapshot <= mrp_paise_snapshot),
    CONSTRAINT chk_order_items_line_subtotal            CHECK (line_subtotal_paise >= 0),
    CONSTRAINT chk_order_items_line_discount            CHECK (line_discount_paise >= 0),
    CONSTRAINT chk_order_items_line_total               CHECK (line_total_paise >= 0)
);

COMMENT ON TABLE order_items IS
    'Immutable product snapshot for each order line. '
    'All snapshot columns are set at order creation and never updated. '
    'product_id FK is nullable (ON DELETE SET NULL) to survive rare hard-deletes.';

-- ---------------------------------------------------------------------------
-- TABLE: order_status_history
-- Append-only record of every status transition.
--
-- from_status: NULL only for the initial 'pending' record (no prior state).
-- changed_by_user_id: populated when the customer initiated the change
--   (e.g. customer-initiated cancellation).
-- changed_by_admin_user_id: populated when an admin initiated the change.
-- Exactly one of these should be non-NULL per row (enforced by application).
--
-- Rows are never updated or deleted in normal operations.
-- ---------------------------------------------------------------------------
CREATE TABLE order_status_history (
    id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id                UUID        NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
    from_status             order_status,                   -- NULL for initial 'pending'
    to_status               order_status NOT NULL,
    changed_by_user_id      UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
    changed_by_admin_user_id UUID       REFERENCES admin_users(id) ON DELETE SET NULL,
    reason                  TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Cannot have both user and admin as the actor
    CONSTRAINT chk_order_history_single_actor
        CHECK (
            changed_by_user_id IS NULL OR changed_by_admin_user_id IS NULL
        )
);

COMMENT ON TABLE order_status_history IS
    'Immutable append-only log of all order status transitions. '
    'from_status is NULL only for the initial pending record. '
    'Exactly one of changed_by_user_id or changed_by_admin_user_id should be non-NULL.';

-- ---------------------------------------------------------------------------
-- TABLE: payments
-- Payment record associated with an order.
--
-- In v1 (COD only): one payment row per order, method = cash_on_delivery,
-- status starts as 'pending'. No gateway integration exists.
--
-- provider, provider_payment_id, provider_order_id:
--   NULL for COD. Populated for future online payment methods.
--   The schema supports future gateway data without migration.
--
-- ON DELETE RESTRICT: payment records are historical; order cannot be
-- casually deleted while a payment row references it.
-- ---------------------------------------------------------------------------
CREATE TABLE payments (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id            UUID            NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,
    payment_method      payment_method  NOT NULL,
    status              payment_status  NOT NULL DEFAULT 'pending',
    amount_paise        INTEGER         NOT NULL,
    provider            TEXT,                   -- NULL for COD; e.g. 'razorpay' for future
    provider_payment_id TEXT,
    provider_order_id   TEXT,
    metadata            JSONB           DEFAULT '{}',
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_payments_amount CHECK (amount_paise >= 0)
);

COMMENT ON TABLE payments IS
    'Payment record per order. In v1 (COD), status starts as pending and '
    'is never automatically moved to paid (physical collection is out-of-scope). '
    'provider fields are NULL for COD; populated by future gateway integration.';

-- =============================================================================
-- RESOLVE DEFERRED FOREIGN KEYS
-- These FKs were omitted from migrations 004 and 007 to break circular
-- dependencies. Now that orders exists, the constraints can be added.
-- =============================================================================

-- inventory_transactions.order_id → orders
ALTER TABLE inventory_transactions
    ADD CONSTRAINT fk_inventory_transactions_order
    FOREIGN KEY (order_id)
    REFERENCES orders(id)
    ON DELETE SET NULL;

COMMENT ON CONSTRAINT fk_inventory_transactions_order
    ON inventory_transactions IS
    'Deferred FK: added in migration 008 after orders table is created. '
    'ON DELETE SET NULL: order deletion (emergency only) does not erase '
    'the inventory transaction ledger entry.';

-- coupon_usage.order_id → orders
ALTER TABLE coupon_usage
    ADD CONSTRAINT fk_coupon_usage_order
    FOREIGN KEY (order_id)
    REFERENCES orders(id)
    ON DELETE SET NULL;

-- Unique constraint: one coupon redemption per order
ALTER TABLE coupon_usage
    ADD CONSTRAINT uq_coupon_usage_order
    UNIQUE (order_id);

COMMENT ON CONSTRAINT fk_coupon_usage_order ON coupon_usage IS
    'Deferred FK: added in migration 008 after orders table is created.';

-- =============================================================================
-- END OF MIGRATION 008
-- =============================================================================
